# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: anki/collection.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from .. import (
    generic as _generic__,
    sync as _sync__,
)

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class OpenCollectionRequest(betterproto.Message):
    collection_path: str = betterproto.string_field(1)
    media_folder_path: str = betterproto.string_field(2)
    media_db_path: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class CloseCollectionRequest(betterproto.Message):
    downgrade_to_schema11: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class CheckDatabaseResponse(betterproto.Message):
    problems: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class OpChanges(betterproto.Message):
    card: bool = betterproto.bool_field(1)
    note: bool = betterproto.bool_field(2)
    deck: bool = betterproto.bool_field(3)
    tag: bool = betterproto.bool_field(4)
    notetype: bool = betterproto.bool_field(5)
    config: bool = betterproto.bool_field(6)
    deck_config: bool = betterproto.bool_field(11)
    mtime: bool = betterproto.bool_field(12)
    browser_table: bool = betterproto.bool_field(7)
    browser_sidebar: bool = betterproto.bool_field(8)
    note_text: bool = betterproto.bool_field(9)
    """editor and displayed card in review screen"""

    study_queues: bool = betterproto.bool_field(10)
    """whether to call .reset() and getCard()"""


@dataclass(eq=False, repr=False)
class OpChangesOnly(betterproto.Message):
    """
    Allows frontend code to extract changes from other messages like
     ImportResponse without decoding other potentially large fields.
    """

    changes: "OpChanges" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class OpChangesWithCount(betterproto.Message):
    changes: "OpChanges" = betterproto.message_field(1)
    count: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class OpChangesWithId(betterproto.Message):
    changes: "OpChanges" = betterproto.message_field(1)
    id: int = betterproto.int64_field(2)


@dataclass(eq=False, repr=False)
class UndoStatus(betterproto.Message):
    undo: str = betterproto.string_field(1)
    redo: str = betterproto.string_field(2)
    last_step: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class OpChangesAfterUndo(betterproto.Message):
    changes: "OpChanges" = betterproto.message_field(1)
    operation: str = betterproto.string_field(2)
    reverted_to_timestamp: int = betterproto.int64_field(3)
    new_status: "UndoStatus" = betterproto.message_field(4)
    counter: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class Progress(betterproto.Message):
    none: "_generic__.Empty" = betterproto.message_field(1, group="value")
    media_sync: "_sync__.MediaSyncProgress" = betterproto.message_field(
        2, group="value"
    )
    media_check: str = betterproto.string_field(3, group="value")
    full_sync: "ProgressFullSync" = betterproto.message_field(4, group="value")
    normal_sync: "ProgressNormalSync" = betterproto.message_field(5, group="value")
    database_check: "ProgressDatabaseCheck" = betterproto.message_field(
        6, group="value"
    )
    importing: str = betterproto.string_field(7, group="value")
    exporting: str = betterproto.string_field(8, group="value")
    compute_params: "ComputeParamsProgress" = betterproto.message_field(
        9, group="value"
    )
    compute_retention: "ComputeRetentionProgress" = betterproto.message_field(
        10, group="value"
    )
    compute_memory: "ComputeMemoryProgress" = betterproto.message_field(
        11, group="value"
    )


@dataclass(eq=False, repr=False)
class ProgressFullSync(betterproto.Message):
    transferred: int = betterproto.uint32_field(1)
    total: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class ProgressNormalSync(betterproto.Message):
    stage: str = betterproto.string_field(1)
    added: str = betterproto.string_field(2)
    removed: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ProgressDatabaseCheck(betterproto.Message):
    stage: str = betterproto.string_field(1)
    stage_total: int = betterproto.uint32_field(2)
    stage_current: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class ComputeParamsProgress(betterproto.Message):
    current: int = betterproto.uint32_field(1)
    """Current iteration"""

    total: int = betterproto.uint32_field(2)
    """Total iterations"""

    reviews: int = betterproto.uint32_field(3)
    current_preset: int = betterproto.uint32_field(4)
    """Only used in 'compute all params' case"""

    total_presets: int = betterproto.uint32_field(5)
    """Only used in 'compute all params' case"""


@dataclass(eq=False, repr=False)
class ComputeRetentionProgress(betterproto.Message):
    current: int = betterproto.uint32_field(1)
    total: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class ComputeMemoryProgress(betterproto.Message):
    current_cards: int = betterproto.uint32_field(1)
    total_cards: int = betterproto.uint32_field(2)
    label: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class CreateBackupRequest(betterproto.Message):
    backup_folder: str = betterproto.string_field(1)
    force: bool = betterproto.bool_field(2)
    """Create a backup even if the configured interval hasn't elapsed yet."""

    wait_for_completion: bool = betterproto.bool_field(3)


@dataclass(eq=False, repr=False)
class GetCustomColoursResponse(betterproto.Message):
    colours: List[str] = betterproto.string_field(1)


class CollectionServiceStub(betterproto.ServiceStub):
    async def check_database(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CheckDatabaseResponse":
        return await self._unary_unary(
            "/anki.collection.CollectionService/CheckDatabase",
            generic_empty,
            CheckDatabaseResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_undo_status(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "UndoStatus":
        return await self._unary_unary(
            "/anki.collection.CollectionService/GetUndoStatus",
            generic_empty,
            UndoStatus,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def undo(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OpChangesAfterUndo":
        return await self._unary_unary(
            "/anki.collection.CollectionService/Undo",
            generic_empty,
            OpChangesAfterUndo,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def redo(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OpChangesAfterUndo":
        return await self._unary_unary(
            "/anki.collection.CollectionService/Redo",
            generic_empty,
            OpChangesAfterUndo,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def add_custom_undo_entry(
        self,
        generic_string: "_generic__.String",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.UInt32":
        return await self._unary_unary(
            "/anki.collection.CollectionService/AddCustomUndoEntry",
            generic_string,
            _generic__.UInt32,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def merge_undo_entries(
        self,
        generic_u_int32: "_generic__.UInt32",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OpChanges":
        return await self._unary_unary(
            "/anki.collection.CollectionService/MergeUndoEntries",
            generic_u_int32,
            OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def latest_progress(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Progress":
        return await self._unary_unary(
            "/anki.collection.CollectionService/LatestProgress",
            generic_empty,
            Progress,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_wants_abort(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Empty":
        return await self._unary_unary(
            "/anki.collection.CollectionService/SetWantsAbort",
            generic_empty,
            _generic__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_load_balancer_enabled(
        self,
        generic_bool: "_generic__.Bool",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OpChanges":
        return await self._unary_unary(
            "/anki.collection.CollectionService/SetLoadBalancerEnabled",
            generic_bool,
            OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_custom_colours(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetCustomColoursResponse":
        return await self._unary_unary(
            "/anki.collection.CollectionService/GetCustomColours",
            generic_empty,
            GetCustomColoursResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class BackendCollectionServiceStub(betterproto.ServiceStub):
    async def open_collection(
        self,
        open_collection_request: "OpenCollectionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Empty":
        return await self._unary_unary(
            "/anki.collection.BackendCollectionService/OpenCollection",
            open_collection_request,
            _generic__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def close_collection(
        self,
        close_collection_request: "CloseCollectionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Empty":
        return await self._unary_unary(
            "/anki.collection.BackendCollectionService/CloseCollection",
            close_collection_request,
            _generic__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def create_backup(
        self,
        create_backup_request: "CreateBackupRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Bool":
        return await self._unary_unary(
            "/anki.collection.BackendCollectionService/CreateBackup",
            create_backup_request,
            _generic__.Bool,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def await_backup_completion(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Empty":
        return await self._unary_unary(
            "/anki.collection.BackendCollectionService/AwaitBackupCompletion",
            generic_empty,
            _generic__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def latest_progress(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Progress":
        return await self._unary_unary(
            "/anki.collection.BackendCollectionService/LatestProgress",
            generic_empty,
            Progress,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_wants_abort(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Empty":
        return await self._unary_unary(
            "/anki.collection.BackendCollectionService/SetWantsAbort",
            generic_empty,
            _generic__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class CollectionServiceBase(ServiceBase):

    async def check_database(
        self, generic_empty: "_generic__.Empty"
    ) -> "CheckDatabaseResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_undo_status(self, generic_empty: "_generic__.Empty") -> "UndoStatus":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def undo(self, generic_empty: "_generic__.Empty") -> "OpChangesAfterUndo":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def redo(self, generic_empty: "_generic__.Empty") -> "OpChangesAfterUndo":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def add_custom_undo_entry(
        self, generic_string: "_generic__.String"
    ) -> "_generic__.UInt32":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def merge_undo_entries(
        self, generic_u_int32: "_generic__.UInt32"
    ) -> "OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def latest_progress(self, generic_empty: "_generic__.Empty") -> "Progress":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_wants_abort(
        self, generic_empty: "_generic__.Empty"
    ) -> "_generic__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_load_balancer_enabled(
        self, generic_bool: "_generic__.Bool"
    ) -> "OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_custom_colours(
        self, generic_empty: "_generic__.Empty"
    ) -> "GetCustomColoursResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_check_database(
        self, stream: "grpclib.server.Stream[_generic__.Empty, CheckDatabaseResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.check_database(request)
        await stream.send_message(response)

    async def __rpc_get_undo_status(
        self, stream: "grpclib.server.Stream[_generic__.Empty, UndoStatus]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_undo_status(request)
        await stream.send_message(response)

    async def __rpc_undo(
        self, stream: "grpclib.server.Stream[_generic__.Empty, OpChangesAfterUndo]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.undo(request)
        await stream.send_message(response)

    async def __rpc_redo(
        self, stream: "grpclib.server.Stream[_generic__.Empty, OpChangesAfterUndo]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.redo(request)
        await stream.send_message(response)

    async def __rpc_add_custom_undo_entry(
        self, stream: "grpclib.server.Stream[_generic__.String, _generic__.UInt32]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.add_custom_undo_entry(request)
        await stream.send_message(response)

    async def __rpc_merge_undo_entries(
        self, stream: "grpclib.server.Stream[_generic__.UInt32, OpChanges]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.merge_undo_entries(request)
        await stream.send_message(response)

    async def __rpc_latest_progress(
        self, stream: "grpclib.server.Stream[_generic__.Empty, Progress]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.latest_progress(request)
        await stream.send_message(response)

    async def __rpc_set_wants_abort(
        self, stream: "grpclib.server.Stream[_generic__.Empty, _generic__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_wants_abort(request)
        await stream.send_message(response)

    async def __rpc_set_load_balancer_enabled(
        self, stream: "grpclib.server.Stream[_generic__.Bool, OpChanges]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_load_balancer_enabled(request)
        await stream.send_message(response)

    async def __rpc_get_custom_colours(
        self,
        stream: "grpclib.server.Stream[_generic__.Empty, GetCustomColoursResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_custom_colours(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/anki.collection.CollectionService/CheckDatabase": grpclib.const.Handler(
                self.__rpc_check_database,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                CheckDatabaseResponse,
            ),
            "/anki.collection.CollectionService/GetUndoStatus": grpclib.const.Handler(
                self.__rpc_get_undo_status,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                UndoStatus,
            ),
            "/anki.collection.CollectionService/Undo": grpclib.const.Handler(
                self.__rpc_undo,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                OpChangesAfterUndo,
            ),
            "/anki.collection.CollectionService/Redo": grpclib.const.Handler(
                self.__rpc_redo,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                OpChangesAfterUndo,
            ),
            "/anki.collection.CollectionService/AddCustomUndoEntry": grpclib.const.Handler(
                self.__rpc_add_custom_undo_entry,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.String,
                _generic__.UInt32,
            ),
            "/anki.collection.CollectionService/MergeUndoEntries": grpclib.const.Handler(
                self.__rpc_merge_undo_entries,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.UInt32,
                OpChanges,
            ),
            "/anki.collection.CollectionService/LatestProgress": grpclib.const.Handler(
                self.__rpc_latest_progress,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                Progress,
            ),
            "/anki.collection.CollectionService/SetWantsAbort": grpclib.const.Handler(
                self.__rpc_set_wants_abort,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                _generic__.Empty,
            ),
            "/anki.collection.CollectionService/SetLoadBalancerEnabled": grpclib.const.Handler(
                self.__rpc_set_load_balancer_enabled,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Bool,
                OpChanges,
            ),
            "/anki.collection.CollectionService/GetCustomColours": grpclib.const.Handler(
                self.__rpc_get_custom_colours,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                GetCustomColoursResponse,
            ),
        }


class BackendCollectionServiceBase(ServiceBase):

    async def open_collection(
        self, open_collection_request: "OpenCollectionRequest"
    ) -> "_generic__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def close_collection(
        self, close_collection_request: "CloseCollectionRequest"
    ) -> "_generic__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def create_backup(
        self, create_backup_request: "CreateBackupRequest"
    ) -> "_generic__.Bool":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def await_backup_completion(
        self, generic_empty: "_generic__.Empty"
    ) -> "_generic__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def latest_progress(self, generic_empty: "_generic__.Empty") -> "Progress":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_wants_abort(
        self, generic_empty: "_generic__.Empty"
    ) -> "_generic__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_open_collection(
        self, stream: "grpclib.server.Stream[OpenCollectionRequest, _generic__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.open_collection(request)
        await stream.send_message(response)

    async def __rpc_close_collection(
        self, stream: "grpclib.server.Stream[CloseCollectionRequest, _generic__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.close_collection(request)
        await stream.send_message(response)

    async def __rpc_create_backup(
        self, stream: "grpclib.server.Stream[CreateBackupRequest, _generic__.Bool]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.create_backup(request)
        await stream.send_message(response)

    async def __rpc_await_backup_completion(
        self, stream: "grpclib.server.Stream[_generic__.Empty, _generic__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.await_backup_completion(request)
        await stream.send_message(response)

    async def __rpc_latest_progress(
        self, stream: "grpclib.server.Stream[_generic__.Empty, Progress]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.latest_progress(request)
        await stream.send_message(response)

    async def __rpc_set_wants_abort(
        self, stream: "grpclib.server.Stream[_generic__.Empty, _generic__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_wants_abort(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/anki.collection.BackendCollectionService/OpenCollection": grpclib.const.Handler(
                self.__rpc_open_collection,
                grpclib.const.Cardinality.UNARY_UNARY,
                OpenCollectionRequest,
                _generic__.Empty,
            ),
            "/anki.collection.BackendCollectionService/CloseCollection": grpclib.const.Handler(
                self.__rpc_close_collection,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloseCollectionRequest,
                _generic__.Empty,
            ),
            "/anki.collection.BackendCollectionService/CreateBackup": grpclib.const.Handler(
                self.__rpc_create_backup,
                grpclib.const.Cardinality.UNARY_UNARY,
                CreateBackupRequest,
                _generic__.Bool,
            ),
            "/anki.collection.BackendCollectionService/AwaitBackupCompletion": grpclib.const.Handler(
                self.__rpc_await_backup_completion,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                _generic__.Empty,
            ),
            "/anki.collection.BackendCollectionService/LatestProgress": grpclib.const.Handler(
                self.__rpc_latest_progress,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                Progress,
            ),
            "/anki.collection.BackendCollectionService/SetWantsAbort": grpclib.const.Handler(
                self.__rpc_set_wants_abort,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                _generic__.Empty,
            ),
        }
