# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: anki/generic.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class Empty(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class Int32(betterproto.Message):
    val: int = betterproto.sint32_field(1)


@dataclass(eq=False, repr=False)
class UInt32(betterproto.Message):
    val: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class Int64(betterproto.Message):
    val: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class String(betterproto.Message):
    val: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class Json(betterproto.Message):
    json: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class Bool(betterproto.Message):
    val: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class StringList(betterproto.Message):
    vals: List[str] = betterproto.string_field(1)
