# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: anki/sync.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from .. import generic as _generic__

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class SyncStatusResponseRequired(betterproto.Enum):
    NO_CHANGES = 0
    NORMAL_SYNC = 1
    FULL_SYNC = 2


class SyncCollectionResponseChangesRequired(betterproto.Enum):
    NO_CHANGES = 0
    NORMAL_SYNC = 1
    FULL_SYNC = 2
    FULL_DOWNLOAD = 3
    """local collection has no cards; upload not an option"""

    FULL_UPLOAD = 4
    """remote collection has no cards; download not an option"""


@dataclass(eq=False, repr=False)
class SyncAuth(betterproto.Message):
    hkey: str = betterproto.string_field(1)
    endpoint: Optional[str] = betterproto.string_field(2, optional=True)
    io_timeout_secs: Optional[int] = betterproto.uint32_field(3, optional=True)


@dataclass(eq=False, repr=False)
class SyncLoginRequest(betterproto.Message):
    username: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)
    endpoint: Optional[str] = betterproto.string_field(3, optional=True)


@dataclass(eq=False, repr=False)
class SyncStatusResponse(betterproto.Message):
    required: "SyncStatusResponseRequired" = betterproto.enum_field(1)
    new_endpoint: Optional[str] = betterproto.string_field(4, optional=True)


@dataclass(eq=False, repr=False)
class SyncCollectionRequest(betterproto.Message):
    auth: "SyncAuth" = betterproto.message_field(1)
    sync_media: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class SyncCollectionResponse(betterproto.Message):
    host_number: int = betterproto.uint32_field(1)
    server_message: str = betterproto.string_field(2)
    required: "SyncCollectionResponseChangesRequired" = betterproto.enum_field(3)
    new_endpoint: Optional[str] = betterproto.string_field(4, optional=True)
    server_media_usn: int = betterproto.int32_field(5)


@dataclass(eq=False, repr=False)
class MediaSyncStatusResponse(betterproto.Message):
    active: bool = betterproto.bool_field(1)
    progress: "MediaSyncProgress" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class MediaSyncProgress(betterproto.Message):
    checked: str = betterproto.string_field(1)
    added: str = betterproto.string_field(2)
    removed: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class FullUploadOrDownloadRequest(betterproto.Message):
    auth: "SyncAuth" = betterproto.message_field(1)
    upload: bool = betterproto.bool_field(2)
    server_usn: Optional[int] = betterproto.int32_field(3, optional=True)
    """if not provided, media syncing will be skipped"""


class SyncServiceStub(betterproto.ServiceStub):
    pass


class BackendSyncServiceStub(betterproto.ServiceStub):
    async def sync_media(
        self,
        sync_auth: "SyncAuth",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Empty":
        return await self._unary_unary(
            "/anki.sync.BackendSyncService/SyncMedia",
            sync_auth,
            _generic__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def abort_media_sync(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Empty":
        return await self._unary_unary(
            "/anki.sync.BackendSyncService/AbortMediaSync",
            generic_empty,
            _generic__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def media_sync_status(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "MediaSyncStatusResponse":
        return await self._unary_unary(
            "/anki.sync.BackendSyncService/MediaSyncStatus",
            generic_empty,
            MediaSyncStatusResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def sync_login(
        self,
        sync_login_request: "SyncLoginRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SyncAuth":
        return await self._unary_unary(
            "/anki.sync.BackendSyncService/SyncLogin",
            sync_login_request,
            SyncAuth,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def sync_status(
        self,
        sync_auth: "SyncAuth",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SyncStatusResponse":
        return await self._unary_unary(
            "/anki.sync.BackendSyncService/SyncStatus",
            sync_auth,
            SyncStatusResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def sync_collection(
        self,
        sync_collection_request: "SyncCollectionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SyncCollectionResponse":
        return await self._unary_unary(
            "/anki.sync.BackendSyncService/SyncCollection",
            sync_collection_request,
            SyncCollectionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def full_upload_or_download(
        self,
        full_upload_or_download_request: "FullUploadOrDownloadRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Empty":
        return await self._unary_unary(
            "/anki.sync.BackendSyncService/FullUploadOrDownload",
            full_upload_or_download_request,
            _generic__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def abort_sync(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Empty":
        return await self._unary_unary(
            "/anki.sync.BackendSyncService/AbortSync",
            generic_empty,
            _generic__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_custom_certificate(
        self,
        generic_string: "_generic__.String",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Bool":
        return await self._unary_unary(
            "/anki.sync.BackendSyncService/SetCustomCertificate",
            generic_string,
            _generic__.Bool,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SyncServiceBase(ServiceBase):

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {}


class BackendSyncServiceBase(ServiceBase):

    async def sync_media(self, sync_auth: "SyncAuth") -> "_generic__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def abort_media_sync(
        self, generic_empty: "_generic__.Empty"
    ) -> "_generic__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def media_sync_status(
        self, generic_empty: "_generic__.Empty"
    ) -> "MediaSyncStatusResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def sync_login(self, sync_login_request: "SyncLoginRequest") -> "SyncAuth":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def sync_status(self, sync_auth: "SyncAuth") -> "SyncStatusResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def sync_collection(
        self, sync_collection_request: "SyncCollectionRequest"
    ) -> "SyncCollectionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def full_upload_or_download(
        self, full_upload_or_download_request: "FullUploadOrDownloadRequest"
    ) -> "_generic__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def abort_sync(self, generic_empty: "_generic__.Empty") -> "_generic__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_custom_certificate(
        self, generic_string: "_generic__.String"
    ) -> "_generic__.Bool":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_sync_media(
        self, stream: "grpclib.server.Stream[SyncAuth, _generic__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.sync_media(request)
        await stream.send_message(response)

    async def __rpc_abort_media_sync(
        self, stream: "grpclib.server.Stream[_generic__.Empty, _generic__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.abort_media_sync(request)
        await stream.send_message(response)

    async def __rpc_media_sync_status(
        self, stream: "grpclib.server.Stream[_generic__.Empty, MediaSyncStatusResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.media_sync_status(request)
        await stream.send_message(response)

    async def __rpc_sync_login(
        self, stream: "grpclib.server.Stream[SyncLoginRequest, SyncAuth]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.sync_login(request)
        await stream.send_message(response)

    async def __rpc_sync_status(
        self, stream: "grpclib.server.Stream[SyncAuth, SyncStatusResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.sync_status(request)
        await stream.send_message(response)

    async def __rpc_sync_collection(
        self,
        stream: "grpclib.server.Stream[SyncCollectionRequest, SyncCollectionResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.sync_collection(request)
        await stream.send_message(response)

    async def __rpc_full_upload_or_download(
        self,
        stream: "grpclib.server.Stream[FullUploadOrDownloadRequest, _generic__.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.full_upload_or_download(request)
        await stream.send_message(response)

    async def __rpc_abort_sync(
        self, stream: "grpclib.server.Stream[_generic__.Empty, _generic__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.abort_sync(request)
        await stream.send_message(response)

    async def __rpc_set_custom_certificate(
        self, stream: "grpclib.server.Stream[_generic__.String, _generic__.Bool]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_custom_certificate(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/anki.sync.BackendSyncService/SyncMedia": grpclib.const.Handler(
                self.__rpc_sync_media,
                grpclib.const.Cardinality.UNARY_UNARY,
                SyncAuth,
                _generic__.Empty,
            ),
            "/anki.sync.BackendSyncService/AbortMediaSync": grpclib.const.Handler(
                self.__rpc_abort_media_sync,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                _generic__.Empty,
            ),
            "/anki.sync.BackendSyncService/MediaSyncStatus": grpclib.const.Handler(
                self.__rpc_media_sync_status,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                MediaSyncStatusResponse,
            ),
            "/anki.sync.BackendSyncService/SyncLogin": grpclib.const.Handler(
                self.__rpc_sync_login,
                grpclib.const.Cardinality.UNARY_UNARY,
                SyncLoginRequest,
                SyncAuth,
            ),
            "/anki.sync.BackendSyncService/SyncStatus": grpclib.const.Handler(
                self.__rpc_sync_status,
                grpclib.const.Cardinality.UNARY_UNARY,
                SyncAuth,
                SyncStatusResponse,
            ),
            "/anki.sync.BackendSyncService/SyncCollection": grpclib.const.Handler(
                self.__rpc_sync_collection,
                grpclib.const.Cardinality.UNARY_UNARY,
                SyncCollectionRequest,
                SyncCollectionResponse,
            ),
            "/anki.sync.BackendSyncService/FullUploadOrDownload": grpclib.const.Handler(
                self.__rpc_full_upload_or_download,
                grpclib.const.Cardinality.UNARY_UNARY,
                FullUploadOrDownloadRequest,
                _generic__.Empty,
            ),
            "/anki.sync.BackendSyncService/AbortSync": grpclib.const.Handler(
                self.__rpc_abort_sync,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                _generic__.Empty,
            ),
            "/anki.sync.BackendSyncService/SetCustomCertificate": grpclib.const.Handler(
                self.__rpc_set_custom_certificate,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.String,
                _generic__.Bool,
            ),
        }
