# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: anki/decks.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from .. import (
    collection as _collection__,
    generic as _generic__,
)

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class DeckFilteredSearchTermOrder(betterproto.Enum):
    OLDEST_REVIEWED_FIRST = 0
    RANDOM = 1
    INTERVALS_ASCENDING = 2
    INTERVALS_DESCENDING = 3
    LAPSES = 4
    ADDED = 5
    DUE = 6
    REVERSE_ADDED = 7
    RETRIEVABILITY_ASCENDING = 8
    RETRIEVABILITY_DESCENDING = 9
    RELATIVE_OVERDUENESS = 10


class SetDeckCollapsedRequestScope(betterproto.Enum):
    REVIEWER = 0
    BROWSER = 1


@dataclass(eq=False, repr=False)
class DeckId(betterproto.Message):
    did: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class DeckIds(betterproto.Message):
    dids: List[int] = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class Deck(betterproto.Message):
    id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    mtime_secs: int = betterproto.int64_field(3)
    usn: int = betterproto.int32_field(4)
    common: "DeckCommon" = betterproto.message_field(5)
    normal: "DeckNormal" = betterproto.message_field(6, group="kind")
    filtered: "DeckFiltered" = betterproto.message_field(7, group="kind")


@dataclass(eq=False, repr=False)
class DeckCommon(betterproto.Message):
    study_collapsed: bool = betterproto.bool_field(1)
    browser_collapsed: bool = betterproto.bool_field(2)
    last_day_studied: int = betterproto.uint32_field(3)
    new_studied: int = betterproto.int32_field(4)
    review_studied: int = betterproto.int32_field(5)
    milliseconds_studied: int = betterproto.int32_field(7)
    learning_studied: int = betterproto.int32_field(6)
    """
    previously set in the v1 scheduler,
     but not currently used for anything
    """

    other: bytes = betterproto.bytes_field(255)


@dataclass(eq=False, repr=False)
class DeckNormal(betterproto.Message):
    config_id: int = betterproto.int64_field(1)
    extend_new: int = betterproto.uint32_field(2)
    extend_review: int = betterproto.uint32_field(3)
    description: str = betterproto.string_field(4)
    markdown_description: bool = betterproto.bool_field(5)
    review_limit: Optional[int] = betterproto.uint32_field(6, optional=True)
    new_limit: Optional[int] = betterproto.uint32_field(7, optional=True)
    review_limit_today: "DeckNormalDayLimit" = betterproto.message_field(8)
    new_limit_today: "DeckNormalDayLimit" = betterproto.message_field(9)
    desired_retention: Optional[float] = betterproto.float_field(10, optional=True)
    """Deck-specific desired retention override"""


@dataclass(eq=False, repr=False)
class DeckNormalDayLimit(betterproto.Message):
    limit: int = betterproto.uint32_field(1)
    today: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class DeckFiltered(betterproto.Message):
    reschedule: bool = betterproto.bool_field(1)
    search_terms: List["DeckFilteredSearchTerm"] = betterproto.message_field(2)
    delays: List[float] = betterproto.float_field(3)
    """v1 scheduler only"""

    preview_delay: int = betterproto.uint32_field(4)
    """v2 and old v3 scheduler only"""

    preview_again_secs: int = betterproto.uint32_field(7)
    """recent v3 scheduler only; 0 means card will be returned"""

    preview_hard_secs: int = betterproto.uint32_field(5)
    """recent v3 scheduler only; 0 means card will be returned"""

    preview_good_secs: int = betterproto.uint32_field(6)
    """recent v3 scheduler only; 0 means card will be returned"""


@dataclass(eq=False, repr=False)
class DeckFilteredSearchTerm(betterproto.Message):
    search: str = betterproto.string_field(1)
    limit: int = betterproto.uint32_field(2)
    order: "DeckFilteredSearchTermOrder" = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class DeckKindContainer(betterproto.Message):
    """
    a container to store the deck specifics in the DB
     as a tagged enum
    """

    normal: "DeckNormal" = betterproto.message_field(1, group="kind")
    filtered: "DeckFiltered" = betterproto.message_field(2, group="kind")


@dataclass(eq=False, repr=False)
class AddOrUpdateDeckLegacyRequest(betterproto.Message):
    deck: bytes = betterproto.bytes_field(1)
    preserve_usn_and_mtime: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class DeckTreeRequest(betterproto.Message):
    now: int = betterproto.int64_field(1)
    """if non-zero, counts for the provided timestamp will be included"""


@dataclass(eq=False, repr=False)
class DeckTreeNode(betterproto.Message):
    deck_id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    level: int = betterproto.uint32_field(4)
    collapsed: bool = betterproto.bool_field(5)
    review_count: int = betterproto.uint32_field(6)
    """counts after adding children+applying limits"""

    learn_count: int = betterproto.uint32_field(7)
    new_count: int = betterproto.uint32_field(8)
    intraday_learning: int = betterproto.uint32_field(9)
    """card counts without children or limits applied"""

    interday_learning_uncapped: int = betterproto.uint32_field(10)
    new_uncapped: int = betterproto.uint32_field(11)
    review_uncapped: int = betterproto.uint32_field(12)
    total_in_deck: int = betterproto.uint32_field(13)
    total_including_children: int = betterproto.uint32_field(14)
    """with children, without any limits"""

    filtered: bool = betterproto.bool_field(16)
    children: List["DeckTreeNode"] = betterproto.message_field(3)
    """
    low index so key can be packed into a byte, but at bottom
     to make debug output easier to read
    """


@dataclass(eq=False, repr=False)
class SetDeckCollapsedRequest(betterproto.Message):
    deck_id: int = betterproto.int64_field(1)
    collapsed: bool = betterproto.bool_field(2)
    scope: "SetDeckCollapsedRequestScope" = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class GetDeckNamesRequest(betterproto.Message):
    skip_empty_default: bool = betterproto.bool_field(1)
    include_filtered: bool = betterproto.bool_field(2)
    """if unset, implies skip_empty_default"""


@dataclass(eq=False, repr=False)
class DeckNames(betterproto.Message):
    entries: List["DeckNameId"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class DeckNameId(betterproto.Message):
    id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ReparentDecksRequest(betterproto.Message):
    deck_ids: List[int] = betterproto.int64_field(1)
    new_parent: int = betterproto.int64_field(2)


@dataclass(eq=False, repr=False)
class RenameDeckRequest(betterproto.Message):
    deck_id: int = betterproto.int64_field(1)
    new_name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class FilteredDeckForUpdate(betterproto.Message):
    id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    config: "DeckFiltered" = betterproto.message_field(3)
    allow_empty: bool = betterproto.bool_field(4)


class DecksServiceStub(betterproto.ServiceStub):
    async def new_deck(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Deck":
        return await self._unary_unary(
            "/anki.decks.DecksService/NewDeck",
            generic_empty,
            Deck,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def add_deck(
        self,
        deck: "Deck",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChangesWithId":
        return await self._unary_unary(
            "/anki.decks.DecksService/AddDeck",
            deck,
            _collection__.OpChangesWithId,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def add_deck_legacy(
        self,
        generic_json: "_generic__.Json",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChangesWithId":
        return await self._unary_unary(
            "/anki.decks.DecksService/AddDeckLegacy",
            generic_json,
            _collection__.OpChangesWithId,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def add_or_update_deck_legacy(
        self,
        add_or_update_deck_legacy_request: "AddOrUpdateDeckLegacyRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeckId":
        return await self._unary_unary(
            "/anki.decks.DecksService/AddOrUpdateDeckLegacy",
            add_or_update_deck_legacy_request,
            DeckId,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def deck_tree(
        self,
        deck_tree_request: "DeckTreeRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeckTreeNode":
        return await self._unary_unary(
            "/anki.decks.DecksService/DeckTree",
            deck_tree_request,
            DeckTreeNode,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def deck_tree_legacy(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Json":
        return await self._unary_unary(
            "/anki.decks.DecksService/DeckTreeLegacy",
            generic_empty,
            _generic__.Json,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_all_decks_legacy(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Json":
        return await self._unary_unary(
            "/anki.decks.DecksService/GetAllDecksLegacy",
            generic_empty,
            _generic__.Json,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_deck_id_by_name(
        self,
        generic_string: "_generic__.String",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeckId":
        return await self._unary_unary(
            "/anki.decks.DecksService/GetDeckIdByName",
            generic_string,
            DeckId,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_deck(
        self,
        deck_id: "DeckId",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Deck":
        return await self._unary_unary(
            "/anki.decks.DecksService/GetDeck",
            deck_id,
            Deck,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def update_deck(
        self,
        deck: "Deck",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.decks.DecksService/UpdateDeck",
            deck,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def update_deck_legacy(
        self,
        generic_json: "_generic__.Json",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.decks.DecksService/UpdateDeckLegacy",
            generic_json,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_deck_collapsed(
        self,
        set_deck_collapsed_request: "SetDeckCollapsedRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.decks.DecksService/SetDeckCollapsed",
            set_deck_collapsed_request,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_deck_legacy(
        self,
        deck_id: "DeckId",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Json":
        return await self._unary_unary(
            "/anki.decks.DecksService/GetDeckLegacy",
            deck_id,
            _generic__.Json,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_deck_names(
        self,
        get_deck_names_request: "GetDeckNamesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeckNames":
        return await self._unary_unary(
            "/anki.decks.DecksService/GetDeckNames",
            get_deck_names_request,
            DeckNames,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_deck_and_child_names(
        self,
        deck_id: "DeckId",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeckNames":
        return await self._unary_unary(
            "/anki.decks.DecksService/GetDeckAndChildNames",
            deck_id,
            DeckNames,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def new_deck_legacy(
        self,
        generic_bool: "_generic__.Bool",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Json":
        return await self._unary_unary(
            "/anki.decks.DecksService/NewDeckLegacy",
            generic_bool,
            _generic__.Json,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def remove_decks(
        self,
        deck_ids: "DeckIds",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChangesWithCount":
        return await self._unary_unary(
            "/anki.decks.DecksService/RemoveDecks",
            deck_ids,
            _collection__.OpChangesWithCount,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def reparent_decks(
        self,
        reparent_decks_request: "ReparentDecksRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChangesWithCount":
        return await self._unary_unary(
            "/anki.decks.DecksService/ReparentDecks",
            reparent_decks_request,
            _collection__.OpChangesWithCount,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def rename_deck(
        self,
        rename_deck_request: "RenameDeckRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.decks.DecksService/RenameDeck",
            rename_deck_request,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_or_create_filtered_deck(
        self,
        deck_id: "DeckId",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "FilteredDeckForUpdate":
        return await self._unary_unary(
            "/anki.decks.DecksService/GetOrCreateFilteredDeck",
            deck_id,
            FilteredDeckForUpdate,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def add_or_update_filtered_deck(
        self,
        filtered_deck_for_update: "FilteredDeckForUpdate",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChangesWithId":
        return await self._unary_unary(
            "/anki.decks.DecksService/AddOrUpdateFilteredDeck",
            filtered_deck_for_update,
            _collection__.OpChangesWithId,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def filtered_deck_order_labels(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.StringList":
        return await self._unary_unary(
            "/anki.decks.DecksService/FilteredDeckOrderLabels",
            generic_empty,
            _generic__.StringList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_current_deck(
        self,
        deck_id: "DeckId",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.decks.DecksService/SetCurrentDeck",
            deck_id,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_current_deck(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Deck":
        return await self._unary_unary(
            "/anki.decks.DecksService/GetCurrentDeck",
            generic_empty,
            Deck,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class BackendDecksServiceStub(betterproto.ServiceStub):
    pass


class DecksServiceBase(ServiceBase):

    async def new_deck(self, generic_empty: "_generic__.Empty") -> "Deck":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def add_deck(self, deck: "Deck") -> "_collection__.OpChangesWithId":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def add_deck_legacy(
        self, generic_json: "_generic__.Json"
    ) -> "_collection__.OpChangesWithId":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def add_or_update_deck_legacy(
        self, add_or_update_deck_legacy_request: "AddOrUpdateDeckLegacyRequest"
    ) -> "DeckId":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def deck_tree(self, deck_tree_request: "DeckTreeRequest") -> "DeckTreeNode":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def deck_tree_legacy(
        self, generic_empty: "_generic__.Empty"
    ) -> "_generic__.Json":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_all_decks_legacy(
        self, generic_empty: "_generic__.Empty"
    ) -> "_generic__.Json":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_deck_id_by_name(
        self, generic_string: "_generic__.String"
    ) -> "DeckId":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_deck(self, deck_id: "DeckId") -> "Deck":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_deck(self, deck: "Deck") -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_deck_legacy(
        self, generic_json: "_generic__.Json"
    ) -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_deck_collapsed(
        self, set_deck_collapsed_request: "SetDeckCollapsedRequest"
    ) -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_deck_legacy(self, deck_id: "DeckId") -> "_generic__.Json":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_deck_names(
        self, get_deck_names_request: "GetDeckNamesRequest"
    ) -> "DeckNames":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_deck_and_child_names(self, deck_id: "DeckId") -> "DeckNames":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def new_deck_legacy(
        self, generic_bool: "_generic__.Bool"
    ) -> "_generic__.Json":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def remove_decks(
        self, deck_ids: "DeckIds"
    ) -> "_collection__.OpChangesWithCount":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def reparent_decks(
        self, reparent_decks_request: "ReparentDecksRequest"
    ) -> "_collection__.OpChangesWithCount":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def rename_deck(
        self, rename_deck_request: "RenameDeckRequest"
    ) -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_or_create_filtered_deck(
        self, deck_id: "DeckId"
    ) -> "FilteredDeckForUpdate":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def add_or_update_filtered_deck(
        self, filtered_deck_for_update: "FilteredDeckForUpdate"
    ) -> "_collection__.OpChangesWithId":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def filtered_deck_order_labels(
        self, generic_empty: "_generic__.Empty"
    ) -> "_generic__.StringList":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_current_deck(self, deck_id: "DeckId") -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_current_deck(self, generic_empty: "_generic__.Empty") -> "Deck":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_new_deck(
        self, stream: "grpclib.server.Stream[_generic__.Empty, Deck]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.new_deck(request)
        await stream.send_message(response)

    async def __rpc_add_deck(
        self, stream: "grpclib.server.Stream[Deck, _collection__.OpChangesWithId]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.add_deck(request)
        await stream.send_message(response)

    async def __rpc_add_deck_legacy(
        self,
        stream: "grpclib.server.Stream[_generic__.Json, _collection__.OpChangesWithId]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.add_deck_legacy(request)
        await stream.send_message(response)

    async def __rpc_add_or_update_deck_legacy(
        self, stream: "grpclib.server.Stream[AddOrUpdateDeckLegacyRequest, DeckId]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.add_or_update_deck_legacy(request)
        await stream.send_message(response)

    async def __rpc_deck_tree(
        self, stream: "grpclib.server.Stream[DeckTreeRequest, DeckTreeNode]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.deck_tree(request)
        await stream.send_message(response)

    async def __rpc_deck_tree_legacy(
        self, stream: "grpclib.server.Stream[_generic__.Empty, _generic__.Json]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.deck_tree_legacy(request)
        await stream.send_message(response)

    async def __rpc_get_all_decks_legacy(
        self, stream: "grpclib.server.Stream[_generic__.Empty, _generic__.Json]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_all_decks_legacy(request)
        await stream.send_message(response)

    async def __rpc_get_deck_id_by_name(
        self, stream: "grpclib.server.Stream[_generic__.String, DeckId]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_deck_id_by_name(request)
        await stream.send_message(response)

    async def __rpc_get_deck(
        self, stream: "grpclib.server.Stream[DeckId, Deck]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_deck(request)
        await stream.send_message(response)

    async def __rpc_update_deck(
        self, stream: "grpclib.server.Stream[Deck, _collection__.OpChanges]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.update_deck(request)
        await stream.send_message(response)

    async def __rpc_update_deck_legacy(
        self, stream: "grpclib.server.Stream[_generic__.Json, _collection__.OpChanges]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.update_deck_legacy(request)
        await stream.send_message(response)

    async def __rpc_set_deck_collapsed(
        self,
        stream: "grpclib.server.Stream[SetDeckCollapsedRequest, _collection__.OpChanges]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_deck_collapsed(request)
        await stream.send_message(response)

    async def __rpc_get_deck_legacy(
        self, stream: "grpclib.server.Stream[DeckId, _generic__.Json]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_deck_legacy(request)
        await stream.send_message(response)

    async def __rpc_get_deck_names(
        self, stream: "grpclib.server.Stream[GetDeckNamesRequest, DeckNames]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_deck_names(request)
        await stream.send_message(response)

    async def __rpc_get_deck_and_child_names(
        self, stream: "grpclib.server.Stream[DeckId, DeckNames]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_deck_and_child_names(request)
        await stream.send_message(response)

    async def __rpc_new_deck_legacy(
        self, stream: "grpclib.server.Stream[_generic__.Bool, _generic__.Json]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.new_deck_legacy(request)
        await stream.send_message(response)

    async def __rpc_remove_decks(
        self, stream: "grpclib.server.Stream[DeckIds, _collection__.OpChangesWithCount]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.remove_decks(request)
        await stream.send_message(response)

    async def __rpc_reparent_decks(
        self,
        stream: "grpclib.server.Stream[ReparentDecksRequest, _collection__.OpChangesWithCount]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.reparent_decks(request)
        await stream.send_message(response)

    async def __rpc_rename_deck(
        self,
        stream: "grpclib.server.Stream[RenameDeckRequest, _collection__.OpChanges]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.rename_deck(request)
        await stream.send_message(response)

    async def __rpc_get_or_create_filtered_deck(
        self, stream: "grpclib.server.Stream[DeckId, FilteredDeckForUpdate]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_or_create_filtered_deck(request)
        await stream.send_message(response)

    async def __rpc_add_or_update_filtered_deck(
        self,
        stream: "grpclib.server.Stream[FilteredDeckForUpdate, _collection__.OpChangesWithId]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.add_or_update_filtered_deck(request)
        await stream.send_message(response)

    async def __rpc_filtered_deck_order_labels(
        self, stream: "grpclib.server.Stream[_generic__.Empty, _generic__.StringList]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.filtered_deck_order_labels(request)
        await stream.send_message(response)

    async def __rpc_set_current_deck(
        self, stream: "grpclib.server.Stream[DeckId, _collection__.OpChanges]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_current_deck(request)
        await stream.send_message(response)

    async def __rpc_get_current_deck(
        self, stream: "grpclib.server.Stream[_generic__.Empty, Deck]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_current_deck(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/anki.decks.DecksService/NewDeck": grpclib.const.Handler(
                self.__rpc_new_deck,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                Deck,
            ),
            "/anki.decks.DecksService/AddDeck": grpclib.const.Handler(
                self.__rpc_add_deck,
                grpclib.const.Cardinality.UNARY_UNARY,
                Deck,
                _collection__.OpChangesWithId,
            ),
            "/anki.decks.DecksService/AddDeckLegacy": grpclib.const.Handler(
                self.__rpc_add_deck_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Json,
                _collection__.OpChangesWithId,
            ),
            "/anki.decks.DecksService/AddOrUpdateDeckLegacy": grpclib.const.Handler(
                self.__rpc_add_or_update_deck_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                AddOrUpdateDeckLegacyRequest,
                DeckId,
            ),
            "/anki.decks.DecksService/DeckTree": grpclib.const.Handler(
                self.__rpc_deck_tree,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeckTreeRequest,
                DeckTreeNode,
            ),
            "/anki.decks.DecksService/DeckTreeLegacy": grpclib.const.Handler(
                self.__rpc_deck_tree_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                _generic__.Json,
            ),
            "/anki.decks.DecksService/GetAllDecksLegacy": grpclib.const.Handler(
                self.__rpc_get_all_decks_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                _generic__.Json,
            ),
            "/anki.decks.DecksService/GetDeckIdByName": grpclib.const.Handler(
                self.__rpc_get_deck_id_by_name,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.String,
                DeckId,
            ),
            "/anki.decks.DecksService/GetDeck": grpclib.const.Handler(
                self.__rpc_get_deck,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeckId,
                Deck,
            ),
            "/anki.decks.DecksService/UpdateDeck": grpclib.const.Handler(
                self.__rpc_update_deck,
                grpclib.const.Cardinality.UNARY_UNARY,
                Deck,
                _collection__.OpChanges,
            ),
            "/anki.decks.DecksService/UpdateDeckLegacy": grpclib.const.Handler(
                self.__rpc_update_deck_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Json,
                _collection__.OpChanges,
            ),
            "/anki.decks.DecksService/SetDeckCollapsed": grpclib.const.Handler(
                self.__rpc_set_deck_collapsed,
                grpclib.const.Cardinality.UNARY_UNARY,
                SetDeckCollapsedRequest,
                _collection__.OpChanges,
            ),
            "/anki.decks.DecksService/GetDeckLegacy": grpclib.const.Handler(
                self.__rpc_get_deck_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeckId,
                _generic__.Json,
            ),
            "/anki.decks.DecksService/GetDeckNames": grpclib.const.Handler(
                self.__rpc_get_deck_names,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetDeckNamesRequest,
                DeckNames,
            ),
            "/anki.decks.DecksService/GetDeckAndChildNames": grpclib.const.Handler(
                self.__rpc_get_deck_and_child_names,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeckId,
                DeckNames,
            ),
            "/anki.decks.DecksService/NewDeckLegacy": grpclib.const.Handler(
                self.__rpc_new_deck_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Bool,
                _generic__.Json,
            ),
            "/anki.decks.DecksService/RemoveDecks": grpclib.const.Handler(
                self.__rpc_remove_decks,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeckIds,
                _collection__.OpChangesWithCount,
            ),
            "/anki.decks.DecksService/ReparentDecks": grpclib.const.Handler(
                self.__rpc_reparent_decks,
                grpclib.const.Cardinality.UNARY_UNARY,
                ReparentDecksRequest,
                _collection__.OpChangesWithCount,
            ),
            "/anki.decks.DecksService/RenameDeck": grpclib.const.Handler(
                self.__rpc_rename_deck,
                grpclib.const.Cardinality.UNARY_UNARY,
                RenameDeckRequest,
                _collection__.OpChanges,
            ),
            "/anki.decks.DecksService/GetOrCreateFilteredDeck": grpclib.const.Handler(
                self.__rpc_get_or_create_filtered_deck,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeckId,
                FilteredDeckForUpdate,
            ),
            "/anki.decks.DecksService/AddOrUpdateFilteredDeck": grpclib.const.Handler(
                self.__rpc_add_or_update_filtered_deck,
                grpclib.const.Cardinality.UNARY_UNARY,
                FilteredDeckForUpdate,
                _collection__.OpChangesWithId,
            ),
            "/anki.decks.DecksService/FilteredDeckOrderLabels": grpclib.const.Handler(
                self.__rpc_filtered_deck_order_labels,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                _generic__.StringList,
            ),
            "/anki.decks.DecksService/SetCurrentDeck": grpclib.const.Handler(
                self.__rpc_set_current_deck,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeckId,
                _collection__.OpChanges,
            ),
            "/anki.decks.DecksService/GetCurrentDeck": grpclib.const.Handler(
                self.__rpc_get_current_deck,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                Deck,
            ),
        }


class BackendDecksServiceBase(ServiceBase):

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {}
