# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: anki/notetypes.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from .. import (
    collection as _collection__,
)
from .. import (
    generic as _generic__,
)

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class ImageOcclusionField(betterproto.Enum):
    OCCLUSIONS = 0
    IMAGE = 1
    HEADER = 2
    BACK_EXTRA = 3
    COMMENTS = 4


class ClozeField(betterproto.Enum):
    TEXT = 0
    BACK_EXTRA = 1


class NotetypeConfigKind(betterproto.Enum):
    KIND_NORMAL = 0
    KIND_CLOZE = 1


class NotetypeConfigCardRequirementKind(betterproto.Enum):
    KIND_NONE = 0
    KIND_ANY = 1
    KIND_ALL = 2


class StockNotetypeKind(betterproto.Enum):
    KIND_BASIC = 0
    KIND_BASIC_AND_REVERSED = 1
    KIND_BASIC_OPTIONAL_REVERSED = 2
    KIND_BASIC_TYPING = 3
    KIND_CLOZE = 4
    KIND_IMAGE_OCCLUSION = 5


class StockNotetypeOriginalStockKind(betterproto.Enum):
    """
    This is decoupled from Kind to allow us to evolve notetypes over time
     (eg an older notetype might require different JS), and allow us to store
     a type even for notetypes that we don't add by default. Code should not
     assume that the entries here are always +1 from Kind.
    """

    ORIGINAL_STOCK_KIND_UNKNOWN = 0
    ORIGINAL_STOCK_KIND_BASIC = 1
    ORIGINAL_STOCK_KIND_BASIC_AND_REVERSED = 2
    ORIGINAL_STOCK_KIND_BASIC_OPTIONAL_REVERSED = 3
    ORIGINAL_STOCK_KIND_BASIC_TYPING = 4
    ORIGINAL_STOCK_KIND_CLOZE = 5
    ORIGINAL_STOCK_KIND_IMAGE_OCCLUSION = 6


@dataclass(eq=False, repr=False)
class NotetypeId(betterproto.Message):
    ntid: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class Notetype(betterproto.Message):
    id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    mtime_secs: int = betterproto.int64_field(3)
    usn: int = betterproto.sint32_field(4)
    config: "NotetypeConfig" = betterproto.message_field(7)
    fields: list["NotetypeField"] = betterproto.message_field(8)
    templates: list["NotetypeTemplate"] = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class NotetypeConfig(betterproto.Message):
    kind: "NotetypeConfigKind" = betterproto.enum_field(1)
    sort_field_idx: int = betterproto.uint32_field(2)
    css: str = betterproto.string_field(3)
    target_deck_id_unused: int = betterproto.int64_field(4)
    """This is now stored separately; retrieve with DefaultsForAdding()"""

    latex_pre: str = betterproto.string_field(5)
    latex_post: str = betterproto.string_field(6)
    latex_svg: bool = betterproto.bool_field(7)
    reqs: list["NotetypeConfigCardRequirement"] = betterproto.message_field(8)
    original_stock_kind: "StockNotetypeOriginalStockKind" = betterproto.enum_field(9)
    """Only set on notetypes created with Anki 2.1.62+."""

    original_id: int | None = betterproto.int64_field(10, optional=True)
    """the id in the source collection for imported notetypes (Anki 23.10)"""

    other: bytes = betterproto.bytes_field(255)


@dataclass(eq=False, repr=False)
class NotetypeConfigCardRequirement(betterproto.Message):
    card_ord: int = betterproto.uint32_field(1)
    kind: "NotetypeConfigCardRequirementKind" = betterproto.enum_field(2)
    field_ords: list[int] = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class NotetypeField(betterproto.Message):
    ord: "_generic__.UInt32" = betterproto.message_field(1)
    name: str = betterproto.string_field(2)
    config: "NotetypeFieldConfig" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class NotetypeFieldConfig(betterproto.Message):
    sticky: bool = betterproto.bool_field(1)
    rtl: bool = betterproto.bool_field(2)
    font_name: str = betterproto.string_field(3)
    font_size: int = betterproto.uint32_field(4)
    description: str = betterproto.string_field(5)
    plain_text: bool = betterproto.bool_field(6)
    collapsed: bool = betterproto.bool_field(7)
    exclude_from_search: bool = betterproto.bool_field(8)
    id: int | None = betterproto.int64_field(9, optional=True)
    """used for merging notetypes on import (Anki 23.10)"""

    tag: int | None = betterproto.uint32_field(10, optional=True)
    """Can be used to uniquely identify required fields."""

    prevent_deletion: bool = betterproto.bool_field(11)
    other: bytes = betterproto.bytes_field(255)


@dataclass(eq=False, repr=False)
class NotetypeTemplate(betterproto.Message):
    ord: "_generic__.UInt32" = betterproto.message_field(1)
    name: str = betterproto.string_field(2)
    mtime_secs: int = betterproto.int64_field(3)
    usn: int = betterproto.sint32_field(4)
    config: "NotetypeTemplateConfig" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class NotetypeTemplateConfig(betterproto.Message):
    q_format: str = betterproto.string_field(1)
    a_format: str = betterproto.string_field(2)
    q_format_browser: str = betterproto.string_field(3)
    a_format_browser: str = betterproto.string_field(4)
    target_deck_id: int = betterproto.int64_field(5)
    browser_font_name: str = betterproto.string_field(6)
    browser_font_size: int = betterproto.uint32_field(7)
    id: int | None = betterproto.int64_field(8, optional=True)
    """used for merging notetypes on import (Anki 23.10)"""

    other: bytes = betterproto.bytes_field(255)


@dataclass(eq=False, repr=False)
class AddOrUpdateNotetypeRequest(betterproto.Message):
    json: bytes = betterproto.bytes_field(1)
    preserve_usn_and_mtime: bool = betterproto.bool_field(2)
    skip_checks: bool = betterproto.bool_field(3)


@dataclass(eq=False, repr=False)
class UpdateNotetypeLegacyRequest(betterproto.Message):
    json: bytes = betterproto.bytes_field(1)
    skip_checks: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class StockNotetype(betterproto.Message):
    kind: "StockNotetypeKind" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class NotetypeNames(betterproto.Message):
    entries: list["NotetypeNameId"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class NotetypeUseCounts(betterproto.Message):
    entries: list["NotetypeNameIdUseCount"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class NotetypeNameId(betterproto.Message):
    id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class NotetypeNameIdUseCount(betterproto.Message):
    id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    use_count: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class GetAuxConfigKeyRequest(betterproto.Message):
    id: int = betterproto.int64_field(1)
    key: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class GetAuxTemplateConfigKeyRequest(betterproto.Message):
    notetype_id: int = betterproto.int64_field(1)
    card_ordinal: int = betterproto.uint32_field(2)
    key: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class GetChangeNotetypeInfoRequest(betterproto.Message):
    old_notetype_id: int = betterproto.int64_field(1)
    new_notetype_id: int = betterproto.int64_field(2)


@dataclass(eq=False, repr=False)
class ChangeNotetypeRequest(betterproto.Message):
    note_ids: list[int] = betterproto.int64_field(1)
    new_fields: list[int] = betterproto.int32_field(2)
    """
    -1 is used to represent null, as nullable repeated fields
     are unwieldy in protobuf
    """

    new_templates: list[int] = betterproto.int32_field(3)
    old_notetype_id: int = betterproto.int64_field(4)
    new_notetype_id: int = betterproto.int64_field(5)
    current_schema: int = betterproto.int64_field(6)
    old_notetype_name: str = betterproto.string_field(7)
    is_cloze: bool = betterproto.bool_field(8)


@dataclass(eq=False, repr=False)
class ChangeNotetypeInfo(betterproto.Message):
    old_field_names: list[str] = betterproto.string_field(1)
    old_template_names: list[str] = betterproto.string_field(2)
    new_field_names: list[str] = betterproto.string_field(3)
    new_template_names: list[str] = betterproto.string_field(4)
    input: "ChangeNotetypeRequest" = betterproto.message_field(5)
    old_notetype_name: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class RestoreNotetypeToStockRequest(betterproto.Message):
    notetype_id: "NotetypeId" = betterproto.message_field(1)
    force_kind: Optional["StockNotetypeKind"] = betterproto.enum_field(2, optional=True)
    """
    Older notetypes did not store their original stock kind, so we allow the UI
     to pass in an override to use when missing, or for tests.
    """


@dataclass(eq=False, repr=False)
class GetClozeFieldOrdsResponse(betterproto.Message):
    ords: list[int] = betterproto.uint32_field(1)


class NotetypesServiceStub(betterproto.ServiceStub):
    async def add_notetype(
        self,
        notetype: "Notetype",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChangesWithId":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/AddNotetype",
            notetype,
            _collection__.OpChangesWithId,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def update_notetype(
        self,
        notetype: "Notetype",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/UpdateNotetype",
            notetype,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def add_notetype_legacy(
        self,
        generic_json: "_generic__.Json",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChangesWithId":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/AddNotetypeLegacy",
            generic_json,
            _collection__.OpChangesWithId,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def update_notetype_legacy(
        self,
        update_notetype_legacy_request: "UpdateNotetypeLegacyRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/UpdateNotetypeLegacy",
            update_notetype_legacy_request,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def add_or_update_notetype(
        self,
        add_or_update_notetype_request: "AddOrUpdateNotetypeRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "NotetypeId":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/AddOrUpdateNotetype",
            add_or_update_notetype_request,
            NotetypeId,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_stock_notetype_legacy(
        self,
        stock_notetype: "StockNotetype",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Json":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetStockNotetypeLegacy",
            stock_notetype,
            _generic__.Json,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_notetype(
        self,
        notetype_id: "NotetypeId",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Notetype":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetNotetype",
            notetype_id,
            Notetype,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_notetype_legacy(
        self,
        notetype_id: "NotetypeId",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Json":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetNotetypeLegacy",
            notetype_id,
            _generic__.Json,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_notetype_names(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "NotetypeNames":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetNotetypeNames",
            generic_empty,
            NotetypeNames,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_notetype_names_and_counts(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "NotetypeUseCounts":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetNotetypeNamesAndCounts",
            generic_empty,
            NotetypeUseCounts,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_notetype_id_by_name(
        self,
        generic_string: "_generic__.String",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "NotetypeId":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetNotetypeIdByName",
            generic_string,
            NotetypeId,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def remove_notetype(
        self,
        notetype_id: "NotetypeId",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/RemoveNotetype",
            notetype_id,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_aux_notetype_config_key(
        self,
        get_aux_config_key_request: "GetAuxConfigKeyRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.String":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetAuxNotetypeConfigKey",
            get_aux_config_key_request,
            _generic__.String,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_aux_template_config_key(
        self,
        get_aux_template_config_key_request: "GetAuxTemplateConfigKeyRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.String":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetAuxTemplateConfigKey",
            get_aux_template_config_key_request,
            _generic__.String,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_change_notetype_info(
        self,
        get_change_notetype_info_request: "GetChangeNotetypeInfoRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ChangeNotetypeInfo":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetChangeNotetypeInfo",
            get_change_notetype_info_request,
            ChangeNotetypeInfo,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def change_notetype(
        self,
        change_notetype_request: "ChangeNotetypeRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/ChangeNotetype",
            change_notetype_request,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_field_names(
        self,
        notetype_id: "NotetypeId",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.StringList":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetFieldNames",
            notetype_id,
            _generic__.StringList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def restore_notetype_to_stock(
        self,
        restore_notetype_to_stock_request: "RestoreNotetypeToStockRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/RestoreNotetypeToStock",
            restore_notetype_to_stock_request,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_cloze_field_ords(
        self,
        notetype_id: "NotetypeId",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetClozeFieldOrdsResponse":
        return await self._unary_unary(
            "/anki.notetypes.NotetypesService/GetClozeFieldOrds",
            notetype_id,
            GetClozeFieldOrdsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class BackendNotetypesServiceStub(betterproto.ServiceStub):
    pass


class NotetypesServiceBase(ServiceBase):

    async def add_notetype(
        self, notetype: "Notetype"
    ) -> "_collection__.OpChangesWithId":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_notetype(self, notetype: "Notetype") -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def add_notetype_legacy(
        self, generic_json: "_generic__.Json"
    ) -> "_collection__.OpChangesWithId":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_notetype_legacy(
        self, update_notetype_legacy_request: "UpdateNotetypeLegacyRequest"
    ) -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def add_or_update_notetype(
        self, add_or_update_notetype_request: "AddOrUpdateNotetypeRequest"
    ) -> "NotetypeId":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_stock_notetype_legacy(
        self, stock_notetype: "StockNotetype"
    ) -> "_generic__.Json":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_notetype(self, notetype_id: "NotetypeId") -> "Notetype":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_notetype_legacy(self, notetype_id: "NotetypeId") -> "_generic__.Json":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_notetype_names(
        self, generic_empty: "_generic__.Empty"
    ) -> "NotetypeNames":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_notetype_names_and_counts(
        self, generic_empty: "_generic__.Empty"
    ) -> "NotetypeUseCounts":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_notetype_id_by_name(
        self, generic_string: "_generic__.String"
    ) -> "NotetypeId":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def remove_notetype(
        self, notetype_id: "NotetypeId"
    ) -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_aux_notetype_config_key(
        self, get_aux_config_key_request: "GetAuxConfigKeyRequest"
    ) -> "_generic__.String":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_aux_template_config_key(
        self, get_aux_template_config_key_request: "GetAuxTemplateConfigKeyRequest"
    ) -> "_generic__.String":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_change_notetype_info(
        self, get_change_notetype_info_request: "GetChangeNotetypeInfoRequest"
    ) -> "ChangeNotetypeInfo":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def change_notetype(
        self, change_notetype_request: "ChangeNotetypeRequest"
    ) -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_field_names(
        self, notetype_id: "NotetypeId"
    ) -> "_generic__.StringList":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def restore_notetype_to_stock(
        self, restore_notetype_to_stock_request: "RestoreNotetypeToStockRequest"
    ) -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_cloze_field_ords(
        self, notetype_id: "NotetypeId"
    ) -> "GetClozeFieldOrdsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_add_notetype(
        self, stream: "grpclib.server.Stream[Notetype, _collection__.OpChangesWithId]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.add_notetype(request)
        await stream.send_message(response)

    async def __rpc_update_notetype(
        self, stream: "grpclib.server.Stream[Notetype, _collection__.OpChanges]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.update_notetype(request)
        await stream.send_message(response)

    async def __rpc_add_notetype_legacy(
        self,
        stream: "grpclib.server.Stream[_generic__.Json, _collection__.OpChangesWithId]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.add_notetype_legacy(request)
        await stream.send_message(response)

    async def __rpc_update_notetype_legacy(
        self,
        stream: "grpclib.server.Stream[UpdateNotetypeLegacyRequest, _collection__.OpChanges]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.update_notetype_legacy(request)
        await stream.send_message(response)

    async def __rpc_add_or_update_notetype(
        self, stream: "grpclib.server.Stream[AddOrUpdateNotetypeRequest, NotetypeId]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.add_or_update_notetype(request)
        await stream.send_message(response)

    async def __rpc_get_stock_notetype_legacy(
        self, stream: "grpclib.server.Stream[StockNotetype, _generic__.Json]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_stock_notetype_legacy(request)
        await stream.send_message(response)

    async def __rpc_get_notetype(
        self, stream: "grpclib.server.Stream[NotetypeId, Notetype]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_notetype(request)
        await stream.send_message(response)

    async def __rpc_get_notetype_legacy(
        self, stream: "grpclib.server.Stream[NotetypeId, _generic__.Json]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_notetype_legacy(request)
        await stream.send_message(response)

    async def __rpc_get_notetype_names(
        self, stream: "grpclib.server.Stream[_generic__.Empty, NotetypeNames]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_notetype_names(request)
        await stream.send_message(response)

    async def __rpc_get_notetype_names_and_counts(
        self, stream: "grpclib.server.Stream[_generic__.Empty, NotetypeUseCounts]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_notetype_names_and_counts(request)
        await stream.send_message(response)

    async def __rpc_get_notetype_id_by_name(
        self, stream: "grpclib.server.Stream[_generic__.String, NotetypeId]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_notetype_id_by_name(request)
        await stream.send_message(response)

    async def __rpc_remove_notetype(
        self, stream: "grpclib.server.Stream[NotetypeId, _collection__.OpChanges]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.remove_notetype(request)
        await stream.send_message(response)

    async def __rpc_get_aux_notetype_config_key(
        self, stream: "grpclib.server.Stream[GetAuxConfigKeyRequest, _generic__.String]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_aux_notetype_config_key(request)
        await stream.send_message(response)

    async def __rpc_get_aux_template_config_key(
        self,
        stream: "grpclib.server.Stream[GetAuxTemplateConfigKeyRequest, _generic__.String]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_aux_template_config_key(request)
        await stream.send_message(response)

    async def __rpc_get_change_notetype_info(
        self,
        stream: "grpclib.server.Stream[GetChangeNotetypeInfoRequest, ChangeNotetypeInfo]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_change_notetype_info(request)
        await stream.send_message(response)

    async def __rpc_change_notetype(
        self,
        stream: "grpclib.server.Stream[ChangeNotetypeRequest, _collection__.OpChanges]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.change_notetype(request)
        await stream.send_message(response)

    async def __rpc_get_field_names(
        self, stream: "grpclib.server.Stream[NotetypeId, _generic__.StringList]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_field_names(request)
        await stream.send_message(response)

    async def __rpc_restore_notetype_to_stock(
        self,
        stream: "grpclib.server.Stream[RestoreNotetypeToStockRequest, _collection__.OpChanges]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.restore_notetype_to_stock(request)
        await stream.send_message(response)

    async def __rpc_get_cloze_field_ords(
        self, stream: "grpclib.server.Stream[NotetypeId, GetClozeFieldOrdsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_cloze_field_ords(request)
        await stream.send_message(response)

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/anki.notetypes.NotetypesService/AddNotetype": grpclib.const.Handler(
                self.__rpc_add_notetype,
                grpclib.const.Cardinality.UNARY_UNARY,
                Notetype,
                _collection__.OpChangesWithId,
            ),
            "/anki.notetypes.NotetypesService/UpdateNotetype": grpclib.const.Handler(
                self.__rpc_update_notetype,
                grpclib.const.Cardinality.UNARY_UNARY,
                Notetype,
                _collection__.OpChanges,
            ),
            "/anki.notetypes.NotetypesService/AddNotetypeLegacy": grpclib.const.Handler(
                self.__rpc_add_notetype_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Json,
                _collection__.OpChangesWithId,
            ),
            "/anki.notetypes.NotetypesService/UpdateNotetypeLegacy": grpclib.const.Handler(
                self.__rpc_update_notetype_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpdateNotetypeLegacyRequest,
                _collection__.OpChanges,
            ),
            "/anki.notetypes.NotetypesService/AddOrUpdateNotetype": grpclib.const.Handler(
                self.__rpc_add_or_update_notetype,
                grpclib.const.Cardinality.UNARY_UNARY,
                AddOrUpdateNotetypeRequest,
                NotetypeId,
            ),
            "/anki.notetypes.NotetypesService/GetStockNotetypeLegacy": grpclib.const.Handler(
                self.__rpc_get_stock_notetype_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                StockNotetype,
                _generic__.Json,
            ),
            "/anki.notetypes.NotetypesService/GetNotetype": grpclib.const.Handler(
                self.__rpc_get_notetype,
                grpclib.const.Cardinality.UNARY_UNARY,
                NotetypeId,
                Notetype,
            ),
            "/anki.notetypes.NotetypesService/GetNotetypeLegacy": grpclib.const.Handler(
                self.__rpc_get_notetype_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                NotetypeId,
                _generic__.Json,
            ),
            "/anki.notetypes.NotetypesService/GetNotetypeNames": grpclib.const.Handler(
                self.__rpc_get_notetype_names,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                NotetypeNames,
            ),
            "/anki.notetypes.NotetypesService/GetNotetypeNamesAndCounts": grpclib.const.Handler(
                self.__rpc_get_notetype_names_and_counts,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                NotetypeUseCounts,
            ),
            "/anki.notetypes.NotetypesService/GetNotetypeIdByName": grpclib.const.Handler(
                self.__rpc_get_notetype_id_by_name,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.String,
                NotetypeId,
            ),
            "/anki.notetypes.NotetypesService/RemoveNotetype": grpclib.const.Handler(
                self.__rpc_remove_notetype,
                grpclib.const.Cardinality.UNARY_UNARY,
                NotetypeId,
                _collection__.OpChanges,
            ),
            "/anki.notetypes.NotetypesService/GetAuxNotetypeConfigKey": grpclib.const.Handler(
                self.__rpc_get_aux_notetype_config_key,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetAuxConfigKeyRequest,
                _generic__.String,
            ),
            "/anki.notetypes.NotetypesService/GetAuxTemplateConfigKey": grpclib.const.Handler(
                self.__rpc_get_aux_template_config_key,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetAuxTemplateConfigKeyRequest,
                _generic__.String,
            ),
            "/anki.notetypes.NotetypesService/GetChangeNotetypeInfo": grpclib.const.Handler(
                self.__rpc_get_change_notetype_info,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetChangeNotetypeInfoRequest,
                ChangeNotetypeInfo,
            ),
            "/anki.notetypes.NotetypesService/ChangeNotetype": grpclib.const.Handler(
                self.__rpc_change_notetype,
                grpclib.const.Cardinality.UNARY_UNARY,
                ChangeNotetypeRequest,
                _collection__.OpChanges,
            ),
            "/anki.notetypes.NotetypesService/GetFieldNames": grpclib.const.Handler(
                self.__rpc_get_field_names,
                grpclib.const.Cardinality.UNARY_UNARY,
                NotetypeId,
                _generic__.StringList,
            ),
            "/anki.notetypes.NotetypesService/RestoreNotetypeToStock": grpclib.const.Handler(
                self.__rpc_restore_notetype_to_stock,
                grpclib.const.Cardinality.UNARY_UNARY,
                RestoreNotetypeToStockRequest,
                _collection__.OpChanges,
            ),
            "/anki.notetypes.NotetypesService/GetClozeFieldOrds": grpclib.const.Handler(
                self.__rpc_get_cloze_field_ords,
                grpclib.const.Cardinality.UNARY_UNARY,
                NotetypeId,
                GetClozeFieldOrdsResponse,
            ),
        }


class BackendNotetypesServiceBase(ServiceBase):

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {}
