# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: anki/deck_config.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from .. import (
    collection as _collection__,
    decks as _decks__,
    generic as _generic__,
)

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class UpdateDeckConfigsMode(betterproto.Enum):
    NORMAL = 0
    APPLY_TO_CHILDREN = 1
    COMPUTE_ALL_PARAMS = 2


class DeckConfigConfigNewCardInsertOrder(betterproto.Enum):
    NEW_CARD_INSERT_ORDER_DUE = 0
    NEW_CARD_INSERT_ORDER_RANDOM = 1


class DeckConfigConfigNewCardGatherPriority(betterproto.Enum):
    NEW_CARD_GATHER_PRIORITY_DECK = 0
    """
    Decks in alphabetical order (preorder), then ascending position.
     Siblings are consecutive, provided they have the same position.
    """

    NEW_CARD_GATHER_PRIORITY_DECK_THEN_RANDOM_NOTES = 5
    """
    Notes are randomly picked from each deck in alphabetical order.
     Siblings are consecutive, provided they have the same position.
    """

    NEW_CARD_GATHER_PRIORITY_LOWEST_POSITION = 1
    """
    Ascending position.
     Siblings are consecutive, provided they have the same position.
    """

    NEW_CARD_GATHER_PRIORITY_HIGHEST_POSITION = 2
    """
    Descending position.
     Siblings are consecutive, provided they have the same position.
    """

    NEW_CARD_GATHER_PRIORITY_RANDOM_NOTES = 3
    """Siblings are consecutive."""

    NEW_CARD_GATHER_PRIORITY_RANDOM_CARDS = 4
    """Siblings are neither grouped nor ordered."""


class DeckConfigConfigNewCardSortOrder(betterproto.Enum):
    NEW_CARD_SORT_ORDER_TEMPLATE = 0
    """
    Ascending card template ordinal.
     For a given ordinal, cards appear in gather order.
    """

    NEW_CARD_SORT_ORDER_NO_SORT = 1
    """Preserves original gather order (eg deck order)."""

    NEW_CARD_SORT_ORDER_TEMPLATE_THEN_RANDOM = 2
    """
    Ascending card template ordinal.
     For a given ordinal, cards appear in random order.
    """

    NEW_CARD_SORT_ORDER_RANDOM_NOTE_THEN_TEMPLATE = 3
    """Random note order. For a given note, cards appear in template order."""

    NEW_CARD_SORT_ORDER_RANDOM_CARD = 4
    """Fully randomized order."""


class DeckConfigConfigReviewCardOrder(betterproto.Enum):
    REVIEW_CARD_ORDER_DAY = 0
    REVIEW_CARD_ORDER_DAY_THEN_DECK = 1
    REVIEW_CARD_ORDER_DECK_THEN_DAY = 2
    REVIEW_CARD_ORDER_INTERVALS_ASCENDING = 3
    REVIEW_CARD_ORDER_INTERVALS_DESCENDING = 4
    REVIEW_CARD_ORDER_EASE_ASCENDING = 5
    REVIEW_CARD_ORDER_EASE_DESCENDING = 6
    REVIEW_CARD_ORDER_RETRIEVABILITY_ASCENDING = 7
    REVIEW_CARD_ORDER_RETRIEVABILITY_DESCENDING = 11
    REVIEW_CARD_ORDER_RELATIVE_OVERDUENESS = 12
    REVIEW_CARD_ORDER_RANDOM = 8
    REVIEW_CARD_ORDER_ADDED = 9
    REVIEW_CARD_ORDER_REVERSE_ADDED = 10


class DeckConfigConfigReviewMix(betterproto.Enum):
    REVIEW_MIX_MIX_WITH_REVIEWS = 0
    REVIEW_MIX_AFTER_REVIEWS = 1
    REVIEW_MIX_BEFORE_REVIEWS = 2


class DeckConfigConfigLeechAction(betterproto.Enum):
    LEECH_ACTION_SUSPEND = 0
    LEECH_ACTION_TAG_ONLY = 1


class DeckConfigConfigAnswerAction(betterproto.Enum):
    ANSWER_ACTION_BURY_CARD = 0
    ANSWER_ACTION_ANSWER_AGAIN = 1
    ANSWER_ACTION_ANSWER_GOOD = 2
    ANSWER_ACTION_ANSWER_HARD = 3
    ANSWER_ACTION_SHOW_REMINDER = 4


class DeckConfigConfigQuestionAction(betterproto.Enum):
    QUESTION_ACTION_SHOW_ANSWER = 0
    QUESTION_ACTION_SHOW_REMINDER = 1


@dataclass(eq=False, repr=False)
class DeckConfigId(betterproto.Message):
    dcid: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class GetRetentionWorkloadRequest(betterproto.Message):
    w: List[float] = betterproto.float_field(1)
    search: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class GetRetentionWorkloadResponse(betterproto.Message):
    costs: Dict[int, float] = betterproto.map_field(
        1, betterproto.TYPE_UINT32, betterproto.TYPE_FLOAT
    )


@dataclass(eq=False, repr=False)
class GetIgnoredBeforeCountRequest(betterproto.Message):
    ignore_revlogs_before_date: str = betterproto.string_field(1)
    search: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class GetIgnoredBeforeCountResponse(betterproto.Message):
    included: int = betterproto.uint64_field(1)
    total: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class DeckConfig(betterproto.Message):
    id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    mtime_secs: int = betterproto.int64_field(3)
    usn: int = betterproto.int32_field(4)
    config: "DeckConfigConfig" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class DeckConfigConfig(betterproto.Message):
    learn_steps: List[float] = betterproto.float_field(1)
    relearn_steps: List[float] = betterproto.float_field(2)
    fsrs_params_4: List[float] = betterproto.float_field(3)
    fsrs_params_5: List[float] = betterproto.float_field(5)
    fsrs_params_6: List[float] = betterproto.float_field(6)
    new_per_day: int = betterproto.uint32_field(9)
    reviews_per_day: int = betterproto.uint32_field(10)
    new_per_day_minimum: int = betterproto.uint32_field(35)
    """not currently used"""

    initial_ease: float = betterproto.float_field(11)
    easy_multiplier: float = betterproto.float_field(12)
    hard_multiplier: float = betterproto.float_field(13)
    lapse_multiplier: float = betterproto.float_field(14)
    interval_multiplier: float = betterproto.float_field(15)
    maximum_review_interval: int = betterproto.uint32_field(16)
    minimum_lapse_interval: int = betterproto.uint32_field(17)
    graduating_interval_good: int = betterproto.uint32_field(18)
    graduating_interval_easy: int = betterproto.uint32_field(19)
    new_card_insert_order: "DeckConfigConfigNewCardInsertOrder" = (
        betterproto.enum_field(20)
    )
    new_card_gather_priority: "DeckConfigConfigNewCardGatherPriority" = (
        betterproto.enum_field(34)
    )
    new_card_sort_order: "DeckConfigConfigNewCardSortOrder" = betterproto.enum_field(32)
    new_mix: "DeckConfigConfigReviewMix" = betterproto.enum_field(30)
    review_order: "DeckConfigConfigReviewCardOrder" = betterproto.enum_field(33)
    interday_learning_mix: "DeckConfigConfigReviewMix" = betterproto.enum_field(31)
    leech_action: "DeckConfigConfigLeechAction" = betterproto.enum_field(21)
    leech_threshold: int = betterproto.uint32_field(22)
    disable_autoplay: bool = betterproto.bool_field(23)
    cap_answer_time_to_secs: int = betterproto.uint32_field(24)
    show_timer: bool = betterproto.bool_field(25)
    stop_timer_on_answer: bool = betterproto.bool_field(38)
    seconds_to_show_question: float = betterproto.float_field(41)
    seconds_to_show_answer: float = betterproto.float_field(42)
    question_action: "DeckConfigConfigQuestionAction" = betterproto.enum_field(36)
    answer_action: "DeckConfigConfigAnswerAction" = betterproto.enum_field(43)
    wait_for_audio: bool = betterproto.bool_field(44)
    skip_question_when_replaying_answer: bool = betterproto.bool_field(26)
    bury_new: bool = betterproto.bool_field(27)
    bury_reviews: bool = betterproto.bool_field(28)
    bury_interday_learning: bool = betterproto.bool_field(29)
    desired_retention: float = betterproto.float_field(37)
    """for fsrs"""

    ignore_revlogs_before_date: str = betterproto.string_field(46)
    easy_days_percentages: List[float] = betterproto.float_field(4)
    historical_retention: float = betterproto.float_field(40)
    param_search: str = betterproto.string_field(45)
    other: bytes = betterproto.bytes_field(255)


@dataclass(eq=False, repr=False)
class DeckConfigsForUpdate(betterproto.Message):
    all_config: List["DeckConfigsForUpdateConfigWithExtra"] = betterproto.message_field(
        1
    )
    current_deck: "DeckConfigsForUpdateCurrentDeck" = betterproto.message_field(2)
    defaults: "DeckConfig" = betterproto.message_field(3)
    schema_modified: bool = betterproto.bool_field(4)
    card_state_customizer: str = betterproto.string_field(6)
    """only applies to v3 scheduler"""

    new_cards_ignore_review_limit: bool = betterproto.bool_field(7)
    """only applies to v3 scheduler"""

    fsrs: bool = betterproto.bool_field(8)
    fsrs_health_check: bool = betterproto.bool_field(11)
    fsrs_legacy_evaluate: bool = betterproto.bool_field(12)
    apply_all_parent_limits: bool = betterproto.bool_field(9)
    days_since_last_fsrs_optimize: int = betterproto.uint32_field(10)


@dataclass(eq=False, repr=False)
class DeckConfigsForUpdateConfigWithExtra(betterproto.Message):
    config: "DeckConfig" = betterproto.message_field(1)
    use_count: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class DeckConfigsForUpdateCurrentDeck(betterproto.Message):
    name: str = betterproto.string_field(1)
    config_id: int = betterproto.int64_field(2)
    parent_config_ids: List[int] = betterproto.int64_field(3)
    limits: "DeckConfigsForUpdateCurrentDeckLimits" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class DeckConfigsForUpdateCurrentDeckLimits(betterproto.Message):
    review: Optional[int] = betterproto.uint32_field(1, optional=True)
    new: Optional[int] = betterproto.uint32_field(2, optional=True)
    review_today: Optional[int] = betterproto.uint32_field(3, optional=True)
    new_today: Optional[int] = betterproto.uint32_field(4, optional=True)
    review_today_active: bool = betterproto.bool_field(5)
    """Whether review_today applies to today or a past day."""

    new_today_active: bool = betterproto.bool_field(6)
    """Whether new_today applies to today or a past day."""

    desired_retention: Optional[float] = betterproto.float_field(7, optional=True)
    """Deck-specific desired retention override"""


@dataclass(eq=False, repr=False)
class UpdateDeckConfigsRequest(betterproto.Message):
    target_deck_id: int = betterproto.int64_field(1)
    configs: List["DeckConfig"] = betterproto.message_field(2)
    """
    / Unchanged, non-selected configs can be omitted. Deck will
    / be set to whichever entry comes last.
    """

    removed_config_ids: List[int] = betterproto.int64_field(3)
    mode: "UpdateDeckConfigsMode" = betterproto.enum_field(4)
    card_state_customizer: str = betterproto.string_field(5)
    limits: "DeckConfigsForUpdateCurrentDeckLimits" = betterproto.message_field(6)
    new_cards_ignore_review_limit: bool = betterproto.bool_field(7)
    fsrs: bool = betterproto.bool_field(8)
    apply_all_parent_limits: bool = betterproto.bool_field(9)
    fsrs_reschedule: bool = betterproto.bool_field(10)
    fsrs_health_check: bool = betterproto.bool_field(11)


class DeckConfigServiceStub(betterproto.ServiceStub):
    async def add_or_update_deck_config_legacy(
        self,
        generic_json: "_generic__.Json",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeckConfigId":
        return await self._unary_unary(
            "/anki.deck_config.DeckConfigService/AddOrUpdateDeckConfigLegacy",
            generic_json,
            DeckConfigId,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_deck_config(
        self,
        deck_config_id: "DeckConfigId",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeckConfig":
        return await self._unary_unary(
            "/anki.deck_config.DeckConfigService/GetDeckConfig",
            deck_config_id,
            DeckConfig,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def all_deck_config_legacy(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Json":
        return await self._unary_unary(
            "/anki.deck_config.DeckConfigService/AllDeckConfigLegacy",
            generic_empty,
            _generic__.Json,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_deck_config_legacy(
        self,
        deck_config_id: "DeckConfigId",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Json":
        return await self._unary_unary(
            "/anki.deck_config.DeckConfigService/GetDeckConfigLegacy",
            deck_config_id,
            _generic__.Json,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def new_deck_config_legacy(
        self,
        generic_empty: "_generic__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Json":
        return await self._unary_unary(
            "/anki.deck_config.DeckConfigService/NewDeckConfigLegacy",
            generic_empty,
            _generic__.Json,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def remove_deck_config(
        self,
        deck_config_id: "DeckConfigId",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_generic__.Empty":
        return await self._unary_unary(
            "/anki.deck_config.DeckConfigService/RemoveDeckConfig",
            deck_config_id,
            _generic__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_deck_configs_for_update(
        self,
        decks_deck_id: "_decks__.DeckId",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeckConfigsForUpdate":
        return await self._unary_unary(
            "/anki.deck_config.DeckConfigService/GetDeckConfigsForUpdate",
            decks_deck_id,
            DeckConfigsForUpdate,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def update_deck_configs(
        self,
        update_deck_configs_request: "UpdateDeckConfigsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "_collection__.OpChanges":
        return await self._unary_unary(
            "/anki.deck_config.DeckConfigService/UpdateDeckConfigs",
            update_deck_configs_request,
            _collection__.OpChanges,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_ignored_before_count(
        self,
        get_ignored_before_count_request: "GetIgnoredBeforeCountRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetIgnoredBeforeCountResponse":
        return await self._unary_unary(
            "/anki.deck_config.DeckConfigService/GetIgnoredBeforeCount",
            get_ignored_before_count_request,
            GetIgnoredBeforeCountResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_retention_workload(
        self,
        get_retention_workload_request: "GetRetentionWorkloadRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetRetentionWorkloadResponse":
        return await self._unary_unary(
            "/anki.deck_config.DeckConfigService/GetRetentionWorkload",
            get_retention_workload_request,
            GetRetentionWorkloadResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class BackendDeckConfigServiceStub(betterproto.ServiceStub):
    pass


class DeckConfigServiceBase(ServiceBase):

    async def add_or_update_deck_config_legacy(
        self, generic_json: "_generic__.Json"
    ) -> "DeckConfigId":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_deck_config(self, deck_config_id: "DeckConfigId") -> "DeckConfig":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def all_deck_config_legacy(
        self, generic_empty: "_generic__.Empty"
    ) -> "_generic__.Json":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_deck_config_legacy(
        self, deck_config_id: "DeckConfigId"
    ) -> "_generic__.Json":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def new_deck_config_legacy(
        self, generic_empty: "_generic__.Empty"
    ) -> "_generic__.Json":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def remove_deck_config(
        self, deck_config_id: "DeckConfigId"
    ) -> "_generic__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_deck_configs_for_update(
        self, decks_deck_id: "_decks__.DeckId"
    ) -> "DeckConfigsForUpdate":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def update_deck_configs(
        self, update_deck_configs_request: "UpdateDeckConfigsRequest"
    ) -> "_collection__.OpChanges":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_ignored_before_count(
        self, get_ignored_before_count_request: "GetIgnoredBeforeCountRequest"
    ) -> "GetIgnoredBeforeCountResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_retention_workload(
        self, get_retention_workload_request: "GetRetentionWorkloadRequest"
    ) -> "GetRetentionWorkloadResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_add_or_update_deck_config_legacy(
        self, stream: "grpclib.server.Stream[_generic__.Json, DeckConfigId]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.add_or_update_deck_config_legacy(request)
        await stream.send_message(response)

    async def __rpc_get_deck_config(
        self, stream: "grpclib.server.Stream[DeckConfigId, DeckConfig]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_deck_config(request)
        await stream.send_message(response)

    async def __rpc_all_deck_config_legacy(
        self, stream: "grpclib.server.Stream[_generic__.Empty, _generic__.Json]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.all_deck_config_legacy(request)
        await stream.send_message(response)

    async def __rpc_get_deck_config_legacy(
        self, stream: "grpclib.server.Stream[DeckConfigId, _generic__.Json]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_deck_config_legacy(request)
        await stream.send_message(response)

    async def __rpc_new_deck_config_legacy(
        self, stream: "grpclib.server.Stream[_generic__.Empty, _generic__.Json]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.new_deck_config_legacy(request)
        await stream.send_message(response)

    async def __rpc_remove_deck_config(
        self, stream: "grpclib.server.Stream[DeckConfigId, _generic__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.remove_deck_config(request)
        await stream.send_message(response)

    async def __rpc_get_deck_configs_for_update(
        self, stream: "grpclib.server.Stream[_decks__.DeckId, DeckConfigsForUpdate]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_deck_configs_for_update(request)
        await stream.send_message(response)

    async def __rpc_update_deck_configs(
        self,
        stream: "grpclib.server.Stream[UpdateDeckConfigsRequest, _collection__.OpChanges]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.update_deck_configs(request)
        await stream.send_message(response)

    async def __rpc_get_ignored_before_count(
        self,
        stream: "grpclib.server.Stream[GetIgnoredBeforeCountRequest, GetIgnoredBeforeCountResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_ignored_before_count(request)
        await stream.send_message(response)

    async def __rpc_get_retention_workload(
        self,
        stream: "grpclib.server.Stream[GetRetentionWorkloadRequest, GetRetentionWorkloadResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_retention_workload(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/anki.deck_config.DeckConfigService/AddOrUpdateDeckConfigLegacy": grpclib.const.Handler(
                self.__rpc_add_or_update_deck_config_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Json,
                DeckConfigId,
            ),
            "/anki.deck_config.DeckConfigService/GetDeckConfig": grpclib.const.Handler(
                self.__rpc_get_deck_config,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeckConfigId,
                DeckConfig,
            ),
            "/anki.deck_config.DeckConfigService/AllDeckConfigLegacy": grpclib.const.Handler(
                self.__rpc_all_deck_config_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                _generic__.Json,
            ),
            "/anki.deck_config.DeckConfigService/GetDeckConfigLegacy": grpclib.const.Handler(
                self.__rpc_get_deck_config_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeckConfigId,
                _generic__.Json,
            ),
            "/anki.deck_config.DeckConfigService/NewDeckConfigLegacy": grpclib.const.Handler(
                self.__rpc_new_deck_config_legacy,
                grpclib.const.Cardinality.UNARY_UNARY,
                _generic__.Empty,
                _generic__.Json,
            ),
            "/anki.deck_config.DeckConfigService/RemoveDeckConfig": grpclib.const.Handler(
                self.__rpc_remove_deck_config,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeckConfigId,
                _generic__.Empty,
            ),
            "/anki.deck_config.DeckConfigService/GetDeckConfigsForUpdate": grpclib.const.Handler(
                self.__rpc_get_deck_configs_for_update,
                grpclib.const.Cardinality.UNARY_UNARY,
                _decks__.DeckId,
                DeckConfigsForUpdate,
            ),
            "/anki.deck_config.DeckConfigService/UpdateDeckConfigs": grpclib.const.Handler(
                self.__rpc_update_deck_configs,
                grpclib.const.Cardinality.UNARY_UNARY,
                UpdateDeckConfigsRequest,
                _collection__.OpChanges,
            ),
            "/anki.deck_config.DeckConfigService/GetIgnoredBeforeCount": grpclib.const.Handler(
                self.__rpc_get_ignored_before_count,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetIgnoredBeforeCountRequest,
                GetIgnoredBeforeCountResponse,
            ),
            "/anki.deck_config.DeckConfigService/GetRetentionWorkload": grpclib.const.Handler(
                self.__rpc_get_retention_workload,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetRetentionWorkloadRequest,
                GetRetentionWorkloadResponse,
            ),
        }


class BackendDeckConfigServiceBase(ServiceBase):

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {}
