from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Protocol, runtime_checkable

type JSONPrimitive = str | int | float | bool | None
type JSONValue = JSONPrimitive | Mapping[str, "JSONValue"] | Sequence["JSONValue"]


@runtime_checkable
class AnkiBackend(Protocol):
    """Backend contract shared by ankiconnect, direct, and standalone modes."""

    name: str
    collection_path: Path | None

    # Decks
    def get_decks(self) -> list[dict[str, JSONValue]]: ...
    def create_deck(self, name: str) -> dict[str, JSONValue]: ...
    def delete_deck(self, name: str) -> dict[str, JSONValue]: ...

    # Notetypes
    def get_notetypes(self) -> list[dict[str, JSONValue]]: ...
    def get_notetype(self, name: str) -> dict[str, JSONValue]: ...

    # Notes
    def add_note(
        self,
        deck: str,
        notetype: str,
        fields: dict[str, str],
        tags: list[str] | None = None,
    ) -> int: ...
    def add_notes(self, notes: list[dict[str, JSONValue]]) -> list[int | None]: ...
    def update_note(
        self,
        note_id: int,
        fields: dict[str, str] | None = None,
        tags: list[str] | None = None,
    ) -> dict[str, JSONValue]: ...
    def delete_notes(self, note_ids: list[int]) -> dict[str, JSONValue]: ...
    def find_notes(self, query: str) -> list[int]: ...
    def get_note(self, note_id: int) -> dict[str, JSONValue]: ...

    # Cards
    def find_cards(self, query: str) -> list[int]: ...
    def get_card(self, card_id: int) -> dict[str, JSONValue]: ...
    def answer_card(self, card_id: int, ease: int) -> dict[str, JSONValue]: ...
    def suspend_cards(self, card_ids: list[int]) -> dict[str, JSONValue]: ...
    def unsuspend_cards(self, card_ids: list[int]) -> dict[str, JSONValue]: ...
    def get_revlog(self, card_id: int, limit: int = 50) -> list[dict[str, JSONValue]]: ...

    # Tags
    def get_tags(self) -> list[str]: ...
    def add_tags(self, note_ids: list[int], tags: list[str]) -> dict[str, JSONValue]: ...
    def remove_tags(self, note_ids: list[int], tags: list[str]) -> dict[str, JSONValue]: ...

    # Review summary
    def get_due_counts(self, deck: str | None = None) -> dict[str, int]: ...
